// IR -> packages/types/src/{index.ts,generated/*.ts} and packages/validate/src/{index.ts,generated/*.ts}.
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const ir = JSON.parse(await readFile(path.join(root, "codegen", "docc-ir", "ir.json"), "utf8"));

const HEADER = "// Generated by codegen/emit from codegen/docc-ir/ir.json. Do not edit by hand.\n\n";
const SCALAR_TS = { string: "string", integer: "number", number: "number", boolean: "boolean", object: "Record<string, unknown>" };
const SCALAR_CHECK = { string: "r.string", integer: "r.number", number: "r.number", boolean: "r.boolean", object: "r.record" };

// A resource is any dictionary with an id, a single-valued `type` discriminator, and at least one of the
// members Apple's base `Resource` dictionary defines (href is optional there, present only in
// responses). Bare { id, type } objects are resource identifiers in request bodies, not resources.
const RESOURCE_MEMBERS = new Set(["href", "attributes", "relationships", "views", "meta"]);
const resources = ir.dictionaries.filter(
  (d) =>
    d.properties.some((p) => p.name === "id") &&
    d.properties.some((p) => p.name === "type" && p.allowed?.length === 1) &&
    d.properties.some((p) => RESOURCE_MEMBERS.has(p.name)),
);
const resourceNames = new Set(resources.map((d) => d.name));

const singular = (s) => s.replace(/ies$/, "y").replace(/s$/, "");

/**
 * Apple titles each resource page by its plural `type` value, so one song object is documented as
 * `Songs` and everything nested under it inherits the prefix. A single object gets the singular name:
 * "Songs.Relationships.SongsAlbumsRelationship" -> "Song.Relationships.SongAlbumsRelationship".
 * Collections keep their plural (`SongsResponse`, the `Albums` target in that relationship).
 */
function displayName(name) {
  const [root, ...rest] = name.split(".");
  if (!resourceNames.has(root)) return name;
  const s = singular(root);
  const owner = (seg) => (seg.startsWith(root) && /(Relationship|View)$/.test(seg) ? s + seg.slice(root.length) : seg);
  return [s, ...rest.map(owner)].join(".");
}

/** "Songs.Attributes" -> "tSongAttributes" */
const typeName = (name) => "t" + displayName(name).replace(/[^A-Za-z0-9]/g, "");
/** "Songs.Attributes" -> "songAttributes" */
const valueName = (name) => typeName(name).slice(1).replace(/^[A-Z]/, (c) => c.toLowerCase());
const key = (name) => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name));
const doc = (text, indent = "") => (text ? `${indent}/** ${text.replaceAll("*/", "* /")} */\n` : "");
// Apple writes every allowed value as a string, even for integer properties (Ratings.Attributes.value
// lists "-1" and "1"); the wire value is a number, so coerce when the scalar is numeric.
const literals = (values, scalar) =>
  values.map((v) => JSON.stringify(scalar === "integer" || scalar === "number" ? Number(v) : v));

const seen = new Map();
for (const d of ir.dictionaries) {
  const n = typeName(d.name);
  if (seen.has(n)) throw new Error(`${seen.get(n)} and ${d.name} both map to ${n}`);
  seen.set(n, d.name);
}

// ---- files -------------------------------------------------------------------------------------
// One file per family: the first segment of Apple's name, with `<Resource>Response` folded into its
// resource. Families with a single dictionary share common.ts. The resource union gets its own file.

const family = (name) => {
  const first = name.split(".")[0];
  const unwrapped = first.replace(/Response$/, "");
  return resourceNames.has(unwrapped) ? unwrapped : first;
};
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const familySize = new Map();
for (const d of ir.dictionaries) familySize.set(family(d.name), (familySize.get(family(d.name)) ?? 0) + 1);
const fileOf = (name) => {
  const f = family(name);
  return familySize.get(f) === 1 ? "common" : kebab(resourceNames.has(f) ? singular(f) : f);
};
const UNION_FILE = "any-resource";

/** @type {Map<string, object[]>} file -> dictionaries, in IR order */
const files = new Map();
for (const d of ir.dictionaries) {
  const f = fileOf(d.name);
  if (f === UNION_FILE) throw new Error(`${d.name} would share a file with the resource union`);
  files.set(f, [...(files.get(f) ?? []), d]);
}

const refsIn = (node, out = new Set()) => {
  if (node.kind === "ref") out.add(node.name);
  for (const n of [].concat(node.of ?? [])) refsIn(n, out);
  return out;
};
/** Other files a dictionary's properties reference: file -> referenced dictionary names */
function imports(dicts, file) {
  const byFile = new Map();
  for (const d of dicts)
    for (const p of d.properties)
      for (const ref of refsIn(p.type)) {
        const target = fileOf(ref);
        if (target !== file) byFile.set(target, [...(byFile.get(target) ?? []), ref]);
      }
  return [...byFile].sort(([a], [b]) => a.localeCompare(b)).map(([f, names]) => [f, [...new Set(names)].sort()]);
}

// ---- types -------------------------------------------------------------------------------------

function ts(node, allowed) {
  switch (node.kind) {
    case "scalar":
      return allowed ? literals(allowed, node.name).join(" | ") : SCALAR_TS[node.name];
    case "ref":
      return typeName(node.name);
    case "array": {
      const inner = ts(node.of, allowed);
      return inner.includes(" | ") ? `(${inner})[]` : `${inner}[]`;
    }
    case "union":
      return node.of.map((n) => ts(n)).join(" | ");
    default:
      return "unknown";
  }
}

function typesFile(dicts, file) {
  let out = HEADER;
  for (const [f, names] of imports(dicts, file)) out += `import type { ${names.map(typeName).join(", ")} } from "./${f}";\n`;
  if (out !== HEADER) out += "\n";
  for (const d of dicts) {
    out += doc(d.doc);
    if (d.properties.length === 0) {
      out += `export type ${typeName(d.name)} = Record<string, unknown>;\n\n`;
      continue;
    }
    out += `export interface ${typeName(d.name)} {\n`;
    for (const p of d.properties) out += doc(p.doc, "  ") + `  ${key(p.name)}${p.required ? "" : "?"}: ${ts(p.type, p.allowed)};\n`;
    out += "}\n\n";
  }
  return out.trimEnd() + "\n";
}

function typesUnion() {
  let out = HEADER;
  for (const [f, names] of imports([{ properties: resources.map((d) => ({ type: { kind: "ref", name: d.name } })) }], UNION_FILE))
    out += `import type { ${names.map(typeName).join(", ")} } from "./${f}";\n`;
  out += "\n/** Every resource object, discriminated by `type`. */\nexport type tAnyResource =\n";
  out += resources.map((d) => `  | ${typeName(d.name)}`).join("\n") + ";\n\n";
  out += 'export type tResourceType = tAnyResource["type"];\n';
  return out;
}

// ---- validators --------------------------------------------------------------------------------

function check(node, allowed) {
  switch (node.kind) {
    case "scalar":
      return allowed ? `r.literal(${literals(allowed, node.name).join(", ")})` : SCALAR_CHECK[node.name];
    case "ref":
      return `r.lazy(() => ${valueName(node.name)})`;
    case "array":
      return `r.array(${check(node.of, allowed)})`;
    case "union":
      return `r.union(${node.of.map((n) => check(n)).join(", ")})`;
    default:
      return "r.unknown";
  }
}

const VALIDATE_PRELUDE = 'import type * as t from "@open-music-sdk/types";\nimport * as r from "../runtime";\n';

function validateFile(dicts, file) {
  let out = HEADER + VALIDATE_PRELUDE;
  // Cross-file references are cyclic (a song's albums, an album's songs). That is safe: every reference
  // sits behind r.lazy, which resolves at validation time, after all modules have loaded.
  for (const [f, names] of imports(dicts, file)) out += `import { ${names.map(valueName).join(", ")} } from "./${f}";\n`;
  out += "\n";
  for (const d of dicts) {
    const tn = `t.${typeName(d.name)}`;
    if (d.properties.length === 0) {
      out += `export const ${valueName(d.name)}: r.tSchema<${tn}> = r.schema<${tn}>(r.record);\n\n`;
      continue;
    }
    const required = literals(d.properties.filter((p) => p.required).map((p) => p.name));
    out += `export const ${valueName(d.name)}: r.tSchema<${tn}> = r.object<${tn}>(\n  {\n`;
    for (const p of d.properties) out += `    ${key(p.name)}: ${check(p.type, p.allowed)},\n`;
    out += `  },\n  [${required.join(", ")}],\n);\n\n`;
  }
  return out.trimEnd() + "\n";
}

function validateUnion() {
  let out = HEADER + VALIDATE_PRELUDE;
  for (const [f, names] of imports([{ properties: resources.map((d) => ({ type: { kind: "ref", name: d.name } })) }], UNION_FILE))
    out += `import { ${names.map(valueName).join(", ")} } from "./${f}";\n`;
  out += `\n/** Any resource object. */\nexport const anyResource: r.tSchema<t.tAnyResource> = r.schema<t.tAnyResource>(\n`;
  out += `  r.union(${resources.map((d) => `r.lazy(() => ${valueName(d.name)})`).join(", ")}),\n);\n`;
  return out;
}

// ---- write -------------------------------------------------------------------------------------

const fileNames = [...files.keys(), UNION_FILE].sort();
const barrel = (extra = "") => HEADER + fileNames.map((f) => `export * from "./generated/${f}";\n`).join("") + extra;

for (const [pkg, perFile, union, extra] of [
  ["types", typesFile, typesUnion, ""],
  ["validate", validateFile, validateUnion, 'export type { tIssue, tResult, tSchema, tStandardSchemaV1 } from "./runtime";\n'],
]) {
  const src = path.join(root, "packages", pkg, "src");
  const dir = path.join(src, "generated");
  await rm(dir, { recursive: true, force: true });
  await mkdir(dir, { recursive: true });
  for (const [f, dicts] of files) await writeFile(path.join(dir, `${f}.ts`), perFile(dicts, f));
  await writeFile(path.join(dir, `${UNION_FILE}.ts`), union());
  await writeFile(path.join(src, "index.ts"), barrel(extra));
}
console.log(`${ir.dictionaries.length} dictionaries (${resources.length} resources) -> ${fileNames.length} files each in packages/types, packages/validate`);
